name: file_system
description: A new Dart project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.0.0 <3.0.0'

dependencies:
  args: ^2.3.1
  process_run: ^0.12.3+2


